name: Run Robot Framework Smoke Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Robot Framework
      run: |
        pip install --upgrade pip
        pip install robotframework

    - name: Run Robot Tests
      run: |
        robot TestSuites/smoke.robot
