on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Robot Framework
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-selenium2library
          pip install selenium

      - name: Install Chrome Web Driver
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
            mkdir -p $GITHUB_WORKSPACE/chrome\ driver
            cp /usr/lib/chromium-browser/chromedriver $GITHUB_WORKSPACE/chrome\ driver/
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            brew install --cask chromedriver
            mkdir -p $GITHUB_WORKSPACE/chrome\ driver
            cp /usr/local/bin/chromedriver $GITHUB_WORKSPACE/chrome\ driver/
          fi

      - name: Run Robot Tests
        run: |
          robot TestSuites/smoke.robot
